### ISSUE TITLE
PushPublish Listener - cannot compile

### ISSUE THREAD

**Issue by roblangridge** [dotCMS/plugin-seeds#15]
This seed plugin doesn't compile with the provided gradle file.

Classes such as com.dotcms.system.event.local.type.pushpublish.AddedToQueueEvent and anything in the system.event package are not present in dotCMS 4.1.1 jar file.

Compilation error as follows on Mac 10.12.6, Oracle Java 1.8.0_60 

gradle jar leads to:
```
com.dotcms.pushpublish.listener/src/main/java/com/dotcms/pushpublish/listener/PushPublishStartSubscriber.java:8: error: cannot find symbol
    @Subscriber
     ^
  symbol:   class Subscriber
  location: class PushPublishStartSubscriber
23 errors
4 warnings


FAILURE: Build failed with an exception.
```

**Comment by bryanboza** [comment]
Hello @roblangridge, this plugin will be available in the incoming releases, the master branch is a development branch and as the plugin was not created for 4.1.1 it won’t compile with this distribution, this is the current list of supported examples for 4.1.1 https://github.com/dotCMS/plugin-seeds/tree/release-4.1.1/OSGi. 

Thanks!
